version: '3.2'
services:
  bdqueimadas:
    image: terrabrasilis/bdqueimadas-app:v1.0.0
    ports:
      - "39002"
    volumes:
      - /data/apps/bdqueimadas/configurations:/usr/bdqueimadas/configurations
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  bdq-exportacao:
    image: terrabrasilis/bdqueimadas-exportacao:v1.0.0
    ports:
      - "8000"
    volumes:
      - /data/apps/bdqueimadas_exportacao/configurations/config.ini:/usr/exportacao/config.ini
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
