version: '3.2'
services:
  bdqueimadas:
    image: otavioabreu27/recovery_bdq:v1.0.15
    ports:
      - "39002"
    volumes:
      - /data/apps/bdqueimadas/configurations:/usr/bdqueimadas/configurations
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
