version: '3.2'
services:
  bdqueimadas:
    image: bdqueimadas:v1.0.0
    ports:
      - "39002"
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  bdq-exportacao:
    image: bdq-exportacao:v1.0.0
    ports:
      - "8000"
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true